version: "3.8"

services:
  nginx:
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "4242:4242"
    volumes:
      - ./web/:/var/www/html
    networks:
      - network
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    networks:
      - network
    volumes:
      # - ./web/:/var/www/html
      - wordpress_data:/var/www/html

networks:
  network:
    driver: bridge

volumes:
  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      type: volume
      device: ${DATA_DIR}
      o: bind
